/*
 Avalara API Client Library
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of SDK  : 22.1.0
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Avalara.SDK.Api;
using Avalara.SDK.Model;
using Avalara.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Avalara.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AgeVerifyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgeVerifyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgeVerifyRequest
        //private AgeVerifyRequest instance;

        public AgeVerifyRequestTests()
        {
            // TODO uncomment below to create an instance of AgeVerifyRequest
            //instance = new AgeVerifyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgeVerifyRequest
        /// </summary>
        [Fact]
        public void AgeVerifyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgeVerifyRequest
            //Assert.IsType<AgeVerifyRequest>(instance);
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'DOB'
        /// </summary>
        [Fact]
        public void DOBTest()
        {
            // TODO unit test for the property 'DOB'
        }

    }

}
