/*
 Avalara API Client Library
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of SDK  : 22.1.0
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Avalara.SDK.Api;
using Avalara.SDK.Model;
using Avalara.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Avalara.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ShippingVerifyResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShippingVerifyResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShippingVerifyResult
        //private ShippingVerifyResult instance;

        public ShippingVerifyResultTests()
        {
            // TODO uncomment below to create an instance of ShippingVerifyResult
            //instance = new ShippingVerifyResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShippingVerifyResult
        /// </summary>
        [Fact]
        public void ShippingVerifyResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShippingVerifyResult
            //Assert.IsType<ShippingVerifyResult>(instance);
        }


        /// <summary>
        /// Test the property 'Compliant'
        /// </summary>
        [Fact]
        public void CompliantTest()
        {
            // TODO unit test for the property 'Compliant'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SuccessMessages'
        /// </summary>
        [Fact]
        public void SuccessMessagesTest()
        {
            // TODO unit test for the property 'SuccessMessages'
        }
        /// <summary>
        /// Test the property 'FailureMessages'
        /// </summary>
        [Fact]
        public void FailureMessagesTest()
        {
            // TODO unit test for the property 'FailureMessages'
        }
        /// <summary>
        /// Test the property 'FailureCodes'
        /// </summary>
        [Fact]
        public void FailureCodesTest()
        {
            // TODO unit test for the property 'FailureCodes'
        }
        /// <summary>
        /// Test the property 'WarningCodes'
        /// </summary>
        [Fact]
        public void WarningCodesTest()
        {
            // TODO unit test for the property 'WarningCodes'
        }
        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Fact]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }

    }

}
