/*
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 Generated by AVALARA
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AvaTax-REST-V3-DotNet-SDK.Api;
using AvaTax-REST-V3-DotNet-SDK.Model;
using AvaTax-REST-V3-DotNet-SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AvaTax-REST-V3-DotNet-SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AgeVerifyFailureCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgeVerifyFailureCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgeVerifyFailureCode
        //private AgeVerifyFailureCode instance;

        public AgeVerifyFailureCodeTests()
        {
            // TODO uncomment below to create an instance of AgeVerifyFailureCode
            //instance = new AgeVerifyFailureCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgeVerifyFailureCode
        /// </summary>
        [Fact]
        public void AgeVerifyFailureCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgeVerifyFailureCode
            //Assert.IsType<AgeVerifyFailureCode>(instance);
        }



    }

}
