/*
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 Generated by AVALARA
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AvaTax-REST-V3-DotNet-SDK.Api;
using AvaTax-REST-V3-DotNet-SDK.Model;
using AvaTax-REST-V3-DotNet-SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AvaTax-REST-V3-DotNet-SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorDetailsErrorDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorDetailsErrorDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorDetailsErrorDetails
        //private ErrorDetailsErrorDetails instance;

        public ErrorDetailsErrorDetailsTests()
        {
            // TODO uncomment below to create an instance of ErrorDetailsErrorDetails
            //instance = new ErrorDetailsErrorDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorDetailsErrorDetails
        /// </summary>
        [Fact]
        public void ErrorDetailsErrorDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorDetailsErrorDetails
            //Assert.IsType<ErrorDetailsErrorDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FaultCode'
        /// </summary>
        [Fact]
        public void FaultCodeTest()
        {
            // TODO unit test for the property 'FaultCode'
        }
        /// <summary>
        /// Test the property 'HelpLink'
        /// </summary>
        [Fact]
        public void HelpLinkTest()
        {
            // TODO unit test for the property 'HelpLink'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Fact]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }

    }

}
