/*
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 Generated by AVALARA
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AvaTax-REST-V3-DotNet-SDK.Api;
using AvaTax-REST-V3-DotNet-SDK.Model;
using AvaTax-REST-V3-DotNet-SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AvaTax-REST-V3-DotNet-SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorDetailsError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorDetailsErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorDetailsError
        //private ErrorDetailsError instance;

        public ErrorDetailsErrorTests()
        {
            // TODO uncomment below to create an instance of ErrorDetailsError
            //instance = new ErrorDetailsError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorDetailsError
        /// </summary>
        [Fact]
        public void ErrorDetailsErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorDetailsError
            //Assert.IsType<ErrorDetailsError>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

    }

}
