/*
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 Generated by AVALARA
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AvaTax-REST-V3-DotNet-SDK.Api;
using AvaTax-REST-V3-DotNet-SDK.Model;
using AvaTax-REST-V3-DotNet-SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AvaTax-REST-V3-DotNet-SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorDetails
        //private ErrorDetails instance;

        public ErrorDetailsTests()
        {
            // TODO uncomment below to create an instance of ErrorDetails
            //instance = new ErrorDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorDetails
        /// </summary>
        [Fact]
        public void ErrorDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorDetails
            //Assert.IsType<ErrorDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
