/*
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 Generated by AVALARA
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Avalara.ASV.Api;
using Avalara.ASV.Model;
using Avalara.ASV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Avalara.ASV.Test.Model
{
    /// <summary>
    ///  Class for testing AgeVerifyResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgeVerifyResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgeVerifyResult
        //private AgeVerifyResult instance;

        public AgeVerifyResultTests()
        {
            // TODO uncomment below to create an instance of AgeVerifyResult
            //instance = new AgeVerifyResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgeVerifyResult
        /// </summary>
        [Fact]
        public void AgeVerifyResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgeVerifyResult
            //Assert.IsType<AgeVerifyResult>(instance);
        }


        /// <summary>
        /// Test the property 'IsOfAge'
        /// </summary>
        [Fact]
        public void IsOfAgeTest()
        {
            // TODO unit test for the property 'IsOfAge'
        }
        /// <summary>
        /// Test the property 'FailureCodes'
        /// </summary>
        [Fact]
        public void FailureCodesTest()
        {
            // TODO unit test for the property 'FailureCodes'
        }

    }

}
