/*
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 Generated by AVALARA
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using AvaTax-REST-V3-DotNet-SDK.Client;
using AvaTax-REST-V3-DotNet-SDK.Model;

namespace AvaTax-REST-V3-DotNet-SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAgeVerificationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age.
        /// </summary>
        /// <remarks>
        /// The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </remarks>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <returns>AgeVerifyResult</returns>
        AgeVerifyResult VerifyAge(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?));

        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age.
        /// </summary>
        /// <remarks>
        /// The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </remarks>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <returns>ApiResponse of AgeVerifyResult</returns>
        ApiResponse<AgeVerifyResult> VerifyAgeWithHttpInfo(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAgeVerificationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age.
        /// </summary>
        /// <remarks>
        /// The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </remarks>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgeVerifyResult</returns>
        System.Threading.Tasks.Task<AgeVerifyResult> VerifyAgeAsync(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age.
        /// </summary>
        /// <remarks>
        /// The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </remarks>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgeVerifyResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<AgeVerifyResult>> VerifyAgeWithHttpInfoAsync(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAgeVerificationApi : IAgeVerificationApiSync, IAgeVerificationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AgeVerificationApi : IAgeVerificationApi
    {
        private AvaTax-REST-V3-DotNet-SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AgeVerificationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AgeVerificationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgeVerificationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AgeVerificationApi(string basePath)
        {
            this.Configuration = AvaTax-REST-V3-DotNet-SDK.Client.Configuration.MergeConfigurations(
                AvaTax-REST-V3-DotNet-SDK.Client.GlobalConfiguration.Instance,
                new AvaTax-REST-V3-DotNet-SDK.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AvaTax-REST-V3-DotNet-SDK.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AvaTax-REST-V3-DotNet-SDK.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AvaTax-REST-V3-DotNet-SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgeVerificationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AgeVerificationApi(AvaTax-REST-V3-DotNet-SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AvaTax-REST-V3-DotNet-SDK.Client.Configuration.MergeConfigurations(
                AvaTax-REST-V3-DotNet-SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AvaTax-REST-V3-DotNet-SDK.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AvaTax-REST-V3-DotNet-SDK.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AvaTax-REST-V3-DotNet-SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgeVerificationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AgeVerificationApi(AvaTax-REST-V3-DotNet-SDK.Client.ISynchronousClient client, AvaTax-REST-V3-DotNet-SDK.Client.IAsynchronousClient asyncClient, AvaTax-REST-V3-DotNet-SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AvaTax-REST-V3-DotNet-SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AvaTax-REST-V3-DotNet-SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AvaTax-REST-V3-DotNet-SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AvaTax-REST-V3-DotNet-SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AvaTax-REST-V3-DotNet-SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age. The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </summary>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <returns>AgeVerifyResult</returns>
        public AgeVerifyResult VerifyAge(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?))
        {
            AvaTax-REST-V3-DotNet-SDK.Client.ApiResponse<AgeVerifyResult> localVarResponse = VerifyAgeWithHttpInfo(ageVerifyRequest, simulatedFailureCode);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age. The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </summary>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <returns>ApiResponse of AgeVerifyResult</returns>
        public AvaTax-REST-V3-DotNet-SDK.Client.ApiResponse<AgeVerifyResult> VerifyAgeWithHttpInfo(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?))
        {
            // verify the required parameter 'ageVerifyRequest' is set
            if (ageVerifyRequest == null)
                throw new AvaTax-REST-V3-DotNet-SDK.Client.ApiException(400, "Missing required parameter 'ageVerifyRequest' when calling AgeVerificationApi->VerifyAge");

            AvaTax-REST-V3-DotNet-SDK.Client.RequestOptions localVarRequestOptions = new AvaTax-REST-V3-DotNet-SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (simulatedFailureCode != null)
            {
                localVarRequestOptions.QueryParameters.Add(AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.ParameterToMultiMap("", "simulatedFailureCode", simulatedFailureCode));
            }
            localVarRequestOptions.Data = ageVerifyRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
			localVarRequestOptions.HeaderParameters.Add("X-Avalara-Client","22.1.0");
            // make the HTTP request
            var localVarResponse = this.Client.Post<AgeVerifyResult>("/api/v2/ageverification/verify", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyAge", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age. The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </summary>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgeVerifyResult</returns>
        public async System.Threading.Tasks.Task<AgeVerifyResult> VerifyAgeAsync(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            AvaTax-REST-V3-DotNet-SDK.Client.ApiResponse<AgeVerifyResult> localVarResponse = await VerifyAgeWithHttpInfoAsync(ageVerifyRequest, simulatedFailureCode, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Determines whether an individual meets or exceeds the minimum legal drinking age. The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
        /// </summary>
        /// <exception cref="AvaTax-REST-V3-DotNet-SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ageVerifyRequest">Information about the individual whose age is being verified.</param>
        /// <param name="simulatedFailureCode">(Optional) The failure code included in the simulated response of the endpoint. Note that this endpoint is only available in Sandbox for testing purposes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgeVerifyResult)</returns>
        public async System.Threading.Tasks.Task<AvaTax-REST-V3-DotNet-SDK.Client.ApiResponse<AgeVerifyResult>> VerifyAgeWithHttpInfoAsync(AgeVerifyRequest ageVerifyRequest, AgeVerifyFailureCode? simulatedFailureCode = default(AgeVerifyFailureCode?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'ageVerifyRequest' is set
            if (ageVerifyRequest == null)
                throw new AvaTax-REST-V3-DotNet-SDK.Client.ApiException(400, "Missing required parameter 'ageVerifyRequest' when calling AgeVerificationApi->VerifyAge");


            AvaTax-REST-V3-DotNet-SDK.Client.RequestOptions localVarRequestOptions = new AvaTax-REST-V3-DotNet-SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (simulatedFailureCode != null)
            {
                localVarRequestOptions.QueryParameters.Add(AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.ParameterToMultiMap("", "simulatedFailureCode", simulatedFailureCode));
            }
            localVarRequestOptions.Data = ageVerifyRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AvaTax-REST-V3-DotNet-SDK.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
			localVarRequestOptions.HeaderParameters.Add("X-Avalara-Client","22.1.0");
            var localVarResponse = await this.AsynchronousClient.PostAsync<AgeVerifyResult>("/api/v2/ageverification/verify", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyAge", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
