/*
 Avalara API Client Library
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of SDK  : 22.1.0
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Avalara.SDK.Client;
using Avalara.SDK.Api;
using Avalara.SDK.Model;
// uncomment below to import models
//using Avalara.SDK.Model;

namespace Avalara.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing AgeVerificationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AgeVerificationApiTests : IDisposable
    {
        private Avalara.SDK.Api.AgeVerification.AgeVerificationApi instance;
        private ApiClient apiclient;
        public AgeVerificationApiTests()
        {
            Configuration configuration = new Configuration();
            configuration.Environment = AvalaraEnvironment.Sandbox;
            configuration.Username = Environment.GetEnvironmentVariable("SANDBOX_USERNAME");
            configuration.Password = Environment.GetEnvironmentVariable("SANDBOX_PASSWORD");
            
            apiclient = new ApiClient(configuration);

            instance = new SDK.Api.AgeVerification.AgeVerificationApi(apiclient);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgeVerificationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AgeVerificationApi
            Assert.IsType<SDK.Api.AgeVerification.AgeVerificationApi>(instance);
        }

        /// <summary>
        /// Test VerifyAge
        /// </summary>
        [Fact]
        public void VerifyAgeTest()
        {
            SDK.Model.AgeVerification.AgeVerifyRequest ageVerifyRequest = new SDK.Model.AgeVerification.AgeVerifyRequest(
                firstName: "Test",
                lastName: "Person",
                address: new SDK.Model.AgeVerification.AgeVerifyRequestAddress(
                 line1: "255 S King St", postalCode: "98109"),
                dOB: "1970-01-01"
                );

            var response = instance.VerifyAge(ageVerifyRequest);
            Assert.IsType<SDK.Model.AgeVerification.AgeVerifyResult>(response);
        }
    }
}
