/*
 Avalara API Client Library
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of SDK  : 22.1.0
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Avalara.SDK.Client;
using Avalara.SDK.Api;
// uncomment below to import models
//using Avalara.SDK.Model;

namespace Avalara.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing ShippingVerificationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ShippingVerificationApiTests : IDisposable
    {
        private ShippingVerificationApi instance;
        private ApiClient apiclient;
        public ShippingVerificationApiTests()
        {
            Configuration configuration = new Configuration();
            configuration.Environment = AvalaraEnvironment.Sandbox;
            configuration.Username = Environment.GetEnvironmentVariable("SANDBOX_USERNAME");
            configuration.Password = Environment.GetEnvironmentVariable("SANDBOX_PASSWORD");

            apiclient = new ApiClient(configuration);

            instance = new ShippingVerificationApi(apiclient);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShippingVerificationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<ShippingVerificationApi>(instance);
        }

        /// <summary>
        /// Test DeregisterShipment
        /// </summary>
        [Fact]
        public void DeregisterShipmentTest()
        {
            string companyCode = "DEFAULT";
            string transactionCode = "063e1af4-11d3-4489-b8ba-ae1149758df4";
            instance.DeregisterShipment(companyCode, transactionCode);
        }
    }
}
