name: DotNet-CICD

on:
  push:
    #branches: [ main ]
    tags:        
      - 2.*
      - 1.*
  
  #workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "Test1=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test Version
      run: |
        echo $VERSION
        echo ${{ env.VERSION }}
        echo ${{ env.Test1 }}
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v1    
      with:
        dotnet-version: 3.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Package
      run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}
    - name: Test cases
      run: dotnet test --no-build --verbosity normal --configuration Release /p:Version=${VERSION}
    - name: Pack Package
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push Package
      run: dotnet nuget push Avalara.SDK.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN} 
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_TOKEN }}
