name: DotNet- Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  #workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo "SANDBOX_USERNAME=${{ secrets.SANDBOX_USERNAME }}" >> $GITHUB_ENV
        echo "SANDBOX_PASSWORD=${{ secrets.SANDBOX_PASSWORD }}" >> $GITHUB_ENV
    - name: Setup .NET 2.x
      uses: actions/setup-dotnet@v1    
      with:
        dotnet-version: 2.x.x
    - name: Setup .NET 3.x
      uses: actions/setup-dotnet@v1    
      with:
        dotnet-version: 3.x.x
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1    
      with:
        dotnet-version: 5.x.x
    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v1    
      with:
        dotnet-version: 6.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Package
      run: dotnet build --no-restore --configuration Release
    - name: Test cases
      run: dotnet test --no-build --verbosity normal --configuration Release
