/*
 * AvaTax Software Development Kit for C#
 *
 * (c) 2004-2022 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Avalara Shipping Verification only
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *

 * @author     Sachin Baijal <sachin.baijal@avalara.com>
 * @author     Jonathan Wenger <jonathan.wenger@avalara.com>
 * @copyright  2004-2022 Avalara, Inc.
 * @license    https://www.apache.org/licenses/LICENSE-2.0
 * @version    2.4.19
 * @link       https://github.com/avadev/AvaTax-REST-V3-DotNet-SDK
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ShippingVerifyResultLines
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShippingVerifyResultLinesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShippingVerifyResultLines
        //private ShippingVerifyResultLines instance;

        public ShippingVerifyResultLinesTests()
        {
            // TODO uncomment below to create an instance of ShippingVerifyResultLines
            //instance = new ShippingVerifyResultLines();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShippingVerifyResultLines
        /// </summary>
        [Fact]
        public void ShippingVerifyResultLinesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShippingVerifyResultLines
            //Assert.IsType<ShippingVerifyResultLines>(instance);
        }


        /// <summary>
        /// Test the property 'ResultCode'
        /// </summary>
        [Fact]
        public void ResultCodeTest()
        {
            // TODO unit test for the property 'ResultCode'
        }
        /// <summary>
        /// Test the property 'LineNumber'
        /// </summary>
        [Fact]
        public void LineNumberTest()
        {
            // TODO unit test for the property 'LineNumber'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SuccessMessages'
        /// </summary>
        [Fact]
        public void SuccessMessagesTest()
        {
            // TODO unit test for the property 'SuccessMessages'
        }
        /// <summary>
        /// Test the property 'FailureMessages'
        /// </summary>
        [Fact]
        public void FailureMessagesTest()
        {
            // TODO unit test for the property 'FailureMessages'
        }
        /// <summary>
        /// Test the property 'FailureCodes'
        /// </summary>
        [Fact]
        public void FailureCodesTest()
        {
            // TODO unit test for the property 'FailureCodes'
        }

    }

}
